### PR TITLE
feat: add NPWP sessions

### PR DESCRIPTION
**Pull request by cristopher-namchee**
## Overview

This pull request:

1. Adds NPWP OCR endpoint and session retrieval to the SDK. 
2. Refactors the code to reduce duplication.
3. Add related test to NPWP sessions.

### CODE REVIEW

**Comment by sahatnicholas-gdp** [comment]
@cristopher-namchee This already looks good, I think we should add the following in the nextjs example:
1. NPWP sessions
2. KTP and NPWP API endpoints

**Comment by cristopher-namchee** [comment]
@sahatnicholas-gdp NPWP-related API isn't possible right now since the package isn't updated. Should I replace it in the `package.json` to use local package instead?

**Comment by sahatnicholas-gdp** [comment]
@cristopher-namchee No need to change `package.json`. We can use [npm link](https://docs.npmjs.com/cli/v9/commands/npm-link) to test it locally without publishing.

**Comment by cristopher-namchee** [comment]
@sahatnicholas-gdp It's done.

**Comment by cristopher-namchee** [comment]
Wait, let me integrate with the other PRs

**Comment by sahatnicholas-gdp** [comment]
@cristopher-namchee It works! Need to resolve conflicts though.

**Comment by cristopher-namchee** [comment]
@sahatnicholas-gdp should be done

**Review by sahatnicholas-gdp — APPROVED** [review]

**Pull request merged**
